Repository RussTedrake/manipulation, pull requests merged in 2025-09, with the labels that each got.

#476 Add new notebook (1/3) for new Problem Set 1
  book/figures/simple_inverted_pendulum_diagram.svg
  book/intro.html
  book/intro/exercises/02_drake_systems_fundamentals.ipynb
  book/intro/exercises/BUILD.bazel
  manipulation/exercises/intro/BUILD.bazel
  manipulation/exercises/intro/test_intro_fundamentals.py
Labels: requires new pip wheels

#477 Add new notebook (2/3) for new Problem Set 1
  book/intro.html
  book/intro/exercises/03_physics_simulation_and_robots.ipynb
  book/intro/exercises/BUILD.bazel
  manipulation/exercises/intro/BUILD.bazel
  manipulation/exercises/intro/test_physics_simulation_and_robots.py
Labels: requires new pip wheels

#497 Add IK problem in pick planar_manipulation notebook for PS2
  book/pick/exercises/05_planar_manipulator.ipynb
  manipulation/exercises/pick/plot_planar_manipulator.py
  solutions_sha.txt
Labels: requires new pip wheels

#500 update images to point to RussTedrake/manipulation
  book/pick.html
  book/pick/exercises/14_pickplace_initials.ipynb
  solutions_sha.txt
Labels: requires new pip wheels, approved-for-ci

#505 fix unit test to allow for duplicate initials
  book/pick/exercises/14_pickplace_initials.ipynb
  manipulation/exercises/pick/test_pickplace_initials.py
  solutions_sha.txt
Labels: approved-for-ci

#510 update image links in book for exercise 4.11
  book/pose/exercises/11_pickplace_initials_with_geometry.ipynb
  solutions_sha.txt
Labels: approved-for-ci

#515 ps4 notebooks no solution
  book/clutter/exercises/analytic_antipodal_grasps.ipynb
  book/clutter/exercises/normal_estimation_depth.ipynb
  book/pose/exercises/ransac.ipynb
  solutions_sha.txt
Labels: approved-for-ci

#516 add problem 5.6
  book/clutter.html
  book/clutter/exercises/6_grasp_initials.ipynb
  book/clutter/exercises/robot.yaml
  book/clutter/exercises/table.sdf
  manipulation/exercises/clutter/BUILD.bazel
  manipulation/exercises/clutter/test_grasp_letters.py
  solutions_sha.txt
Labels: requires new pip wheels, approved-for-ci

#522 remove autograder from exercise 5.6
  book/clutter/exercises/6_grasp_initials.ipynb
  solutions_sha.txt
Labels: approved-for-ci
